# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-03-27 19:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('familia', '0001_initial'),
        ('persona', '0004_persona_generacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='persona',
            name='familia',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='familia.Familia'),
        ),
    ]
