# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-03-29 09:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('persona', '0005_persona_familia'),
    ]

    operations = [
        migrations.CreateModel(
            name='Parejas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.BooleanField()),
            ],
        ),
        migrations.RemoveField(
            model_name='persona',
            name='sexo',
        ),
        migrations.AddField(
            model_name='persona',
            name='abuelos',
            field=models.ManyToManyField(null=True, related_name='_persona_abuelos_+', to='persona.Persona'),
        ),
        migrations.AddField(
            model_name='persona',
            name='madre',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='madre_persona', to='persona.Persona'),
        ),
        migrations.AddField(
            model_name='persona',
            name='padre',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='padre_persona', to='persona.Persona'),
        ),
        migrations.AddField(
            model_name='persona',
            name='primos',
            field=models.ManyToManyField(null=True, related_name='_persona_primos_+', to='persona.Persona'),
        ),
        migrations.AddField(
            model_name='persona',
            name='tios',
            field=models.ManyToManyField(null=True, to='persona.Persona'),
        ),
        migrations.AddField(
            model_name='parejas',
            name='persona',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='persona.Persona'),
        ),
        migrations.AddField(
            model_name='parejas',
            name='persona2',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pareja', to='persona.Persona'),
        ),
    ]
