# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-03-29 09:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('persona', '0007_persona_hermanos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='persona',
            name='abuelos',
            field=models.ManyToManyField(related_name='_persona_abuelos_+', to='persona.Persona'),
        ),
        migrations.AlterField(
            model_name='persona',
            name='hermanos',
            field=models.ManyToManyField(related_name='_persona_hermanos_+', to='persona.Persona'),
        ),
        migrations.AlterField(
            model_name='persona',
            name='primos',
            field=models.ManyToManyField(related_name='_persona_primos_+', to='persona.Persona'),
        ),
        migrations.AlterField(
            model_name='persona',
            name='tios',
            field=models.ManyToManyField(to='persona.Persona'),
        ),
    ]
