# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-03-29 10:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('persona', '0008_auto_20180329_0411'),
    ]

    operations = [
        migrations.AlterField(
            model_name='persona',
            name='abuelos',
            field=models.ManyToManyField(blank=True, related_name='_persona_abuelos_+', to='persona.Persona'),
        ),
        migrations.AlterField(
            model_name='persona',
            name='hermanos',
            field=models.ManyToManyField(blank=True, related_name='_persona_hermanos_+', to='persona.Persona'),
        ),
        migrations.AlterField(
            model_name='persona',
            name='madre',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='madre_persona', to='persona.Persona'),
        ),
        migrations.AlterField(
            model_name='persona',
            name='padre',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='padre_persona', to='persona.Persona'),
        ),
        migrations.AlterField(
            model_name='persona',
            name='primos',
            field=models.ManyToManyField(blank=True, related_name='_persona_primos_+', to='persona.Persona'),
        ),
    ]
