# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-03-29 10:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('persona', '0009_auto_20180329_0502'),
    ]

    operations = [
        migrations.AlterField(
            model_name='persona',
            name='tios',
            field=models.ManyToManyField(blank=True, to='persona.Persona'),
        ),
    ]
