# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-03-29 10:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('persona', '0010_auto_20180329_0503'),
    ]

    operations = [
        migrations.AddField(
            model_name='persona',
            name='pareja',
            field=models.ManyToManyField(blank=True, related_name='parejas_persona', through='persona.Parejas', to='persona.Persona'),
        ),
        migrations.AlterField(
            model_name='parejas',
            name='persona2',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pareja_persona', to='persona.Persona'),
        ),
    ]
