# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-03-25 21:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('persona', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Parentesco',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Relaciones',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parentesco', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reportes.Parentesco')),
                ('persona', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='persona.Persona')),
                ('persona2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='persona_relacionada', to='persona.Persona')),
            ],
        ),
        migrations.AddField(
            model_name='parentesco',
            name='parientes',
            field=models.ManyToManyField(through='reportes.Relaciones', to='persona.Persona'),
        ),
    ]
