# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-03-27 19:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('persona', '0005_persona_familia'),
        ('reportes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Parejas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.BooleanField()),
                ('persona', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='persona.Persona')),
                ('persona2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pareja', to='persona.Persona')),
            ],
        ),
    ]
