# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-03-29 09:05
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reportes', '0002_parejas'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='parejas',
            name='persona',
        ),
        migrations.RemoveField(
            model_name='parejas',
            name='persona2',
        ),
        migrations.RemoveField(
            model_name='parentesco',
            name='parientes',
        ),
        migrations.RemoveField(
            model_name='relaciones',
            name='parentesco',
        ),
        migrations.RemoveField(
            model_name='relaciones',
            name='persona',
        ),
        migrations.RemoveField(
            model_name='relaciones',
            name='persona2',
        ),
        migrations.DeleteModel(
            name='Parejas',
        ),
        migrations.DeleteModel(
            name='Parentesco',
        ),
        migrations.DeleteModel(
            name='Relaciones',
        ),
    ]
